### ISSUE TITLE
Custom styling for the left and right buttons

### ISSUE THREAD

**Issue by Luid101** [ritxweb/ng2carousel#3]
Is it possible to add custom styling to the left and right button? For example if I wanted it to look like this: 
![image](https://user-images.githubusercontent.com/5737006/82691124-463d7a80-9c12-11ea-8c80-bbfa802145d6.png)
is that possible?

Or is it also possible to create new buttons that hook onto the function that controls next and previous, so I can create my own custom button and use it with the carousel?

**Comment by Luid101** [comment]
btw I really like this carousel, very underrated.

**Comment by ritxweb** [comment]
Hi Luid,

Thanks for using my carousel, it is really rewarding. Right now these buttons have no class themselves, althought you can reffer them as .ng2-custom-carousel-controls button:first-of-type and :last-of-type. But I will write down your suggestion for future releases, thanks!

Best

**Comment by Luid101** [comment]
No worries ritxweb. This helps!

**Comment by ritxweb** [comment]
You are welcome!
